### ISSUE TITLE
RuntimeError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

### ISSUE THREAD

**Issue by shashwattrivedi** [matthew-z/R-net#11]
I am trying to use the Dynamic Pair encoder for some task, I am facing some issue.

In modules/pair_encoder/cells.py, the new_input that is generated has dimension 2
`new_input = torch.cat([inputs, attention_vector], dim=-1)`
 but in modules/dropout.py the RNNDropout expects the dimension of 3
`mask = inputs.new_ones(inputs.size(0), 1, inputs.size(2), requires_grad=False)`

Am I giving wrong input somewhere?

**Comment by matthew-z** [comment]
First, I think I didn't apply RNNDropout inside the Dynamic Pair Encoder, are you modifying the code?

RNNDropout's input tensor should be [Batch x time x embedding_dim].

If you only need to apply dropout on a tensor in [batch x embedding_dim], torch.nn.Dropout will be enough.

**Comment by shashwattrivedi** [comment]
Thanks for the reply,
torch.nn.Dropout worked for me, and I didn't modify the code. RNNDropout is used in Gate Module   which is used in _PairEncodeCell Module
` new_input = self.gate(new_input)`
and this cell is a part of DynamicPairEncoder
```
super().__init__(memory_size, input_size, hidden_size, attention_size,
                         bidirectional, dropout, PairEncodeCell, batch_first=batch_first)
```

**Comment by matthew-z** [comment]
I think I put gate in a wrong location. Could you pull the latest code and try again?

BTW, Dynamic Pair encoder is still a work in progress....so it might not work as we expect. It does not provide any gain but slows down the speed for R-Net currently.
