### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Diison** [matthew-z/R-net#18]
Sorry to bother you, but after I replaced the dataset and embedding URL, and run "python main.py train configs/squad/r-net/hkust.jsonnet", I got the information below:
----------------------------------------------------------------------------------------
  File "/home/anaconda3.7/lib/python3.7/sre_parse.py", line 337, in _class_escape
    raise source.error('bad escape %s' % escape, len(escape))
re.error: bad escape \p at position 257
----------------------------------------------------------------------------------------
Looks like the error is raised by regular expression resolution module. Would you please help to fix it?

**Comment by matthew-z** [comment]
Could you paste the complete stack traceback?

**Comment by Diison** [comment]
Thank you, I have fixed the problem. It caused by the version of AllenNLP. My AllenNLP version is higher than 0.7.2. But there still is a problem that after I install the AllenNLP==0.7.2, my PyTorch version became "0.4.1.post2", so maybe the requirement of this project should be PyTorch==0.4.1.post2.

**Comment by matthew-z** [comment]
You may force pip to install 1.0 pytorch in this case.
