### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by 312shan** [matthew-z/R-net#19]
windows10 system , just get this error "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)" for any config file, it was coursed by allennlp's Params tools 

### error msg
```python3
params = Params.from_file(parameter_filename, overrides, ext_vars=ext_vars)
  File "D:\nlp\env\rnet_v3.6\lib\site-packages\allennlp\common\params.py", line 490, in from_file
    file_dict = json.loads(evaluate_file(params_file, ext_vars=ext_vars))
.....
......
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by matthew-z** [comment]
are you using AllenNLP == 0.7.2?

**Comment by 312shan** [comment]
allennlp==0.9.0
torch==1.4.0 

ps ,I found out that may be this error was coursed by jsonnet package dosen't support windows.

**Comment by matthew-z** [comment]
It is possible. I don't have plan to support Windows, so I will close this issue for now. 
Feel free to reopen it if you find any other cause for this issue.
