### ISSUE TITLE
question about accuracy

### ISSUE THREAD

**Issue by chenjiaxiang** [matthew-z/R-net#4]
hello，i don't find a email address on your homepage，so leave an issue.
I ran your r-net code, and i found the best accuracy is or so 0.66, the result is not as good as result they reported in the paper, you had  pointed out that you directly used glove in char embedding. But the gap shouldn't be so big, i want to know the best result on your machine.
Thanks a lot.
You can reply here or send email to me.   cjx123@mail.ustc.edu.cn

**Comment by matthew-z** [comment]
Sorry, I have not found a way to reproduce the paper’s result. 0.66 is also the result on my machine.

**Comment by chenjiaxiang** [comment]
Thanks, I will try to add char level embedding and run the code

发自我的 iPhone

**Comment by matthew-z** [comment]
Actually, I have added convolutional char embedding in my local dev branch. The performance improved only a little (1%). In their ACL paper, they also reported that the performance decreased by 0.9% F1 score without char embedding.

**Comment by chenjiaxiang** [comment]
I know.thanks lot

发自我的 iPhone
