### ISSUE TITLE
代码中存在一个bug

### ISSUE THREAD

**Issue by Star-in-Sky** [matthew-z/R-net#7]
1. 在使用GPU训练的时候，对RNN 网络的初始化hidden时，默认使用的是hidden.cuda()，如果命令使用的 --device_id 3, 就会出错。
出错位置:  recurrent.py 中的 AttentionEncoder 类中的前向传播forward（）里， 这里的hidden初始化的时候，设置cuda()， 是默认的0, 如果前面设置的不是0, 会出现问题。

**Comment by matthew-z** [comment]
是的....我都偷懒默认了用gpu0    需要调整的话建议先在命令行里CUDA_VISIBLE_DEVICES=3

**Comment by Star-in-Sky** [comment]
我想问一下，你这个模型训练出来最后的精度是多少！谢谢！

**Comment by matthew-z** [comment]
比较低的, 应该是66-70 F1,  可以看看这个TF的实现有比较高的F1

**Comment by Star-in-Sky** [comment]
好的，谢谢！我现在遇到一个问题是，我将百度的DuReader数据处理成SQuAD的数据形式进行训练，出现GPU内存溢出的问题，我追踪了一下，都是在attention那边内存溢出的。大哥有什么好的意见和想法没有？我这边对训练数据进行压缩各方面进行了缩减，内存还是溢出。现在的想法，就是改动代码，在多个GPU上运行，但是这个尝试了一下，bug好多。大哥有什么好的意见么

**Comment by matthew-z** [comment]
看了下DuReader文章和问题的长度远长于SQuAD, 所以对整个句子做Attention会挂. 

你可以改用local attention试试. BTW, 你多少内存会挂呀? 我感觉小点batch size应该没事才对
